/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2015-06-30 09:13:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\n");
      out.write("<!-- Website Template by freewebsitetemplates.com -->\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>Laboratory Website Template</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.10.0.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function () {\n");
      out.write("\talert(\"document.ready\");\n");
      out.write("\t});\n");
      out.write("\t</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t\t<a href=\"index.jsp\" class=\"logo\"><img src=\"images/keLogo.png\" alt=\"\"></a>\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li class=\"selected\">\n");
      out.write("\t\t\t\t<a  onclick=\"showHome()\">home</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<a  onclick=\"showAbout()\">about</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<a onclick=\"showServices()\">services</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<a onclick=\"showLocation()\">our locations</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<!-- <li>\n");
      out.write("\t\t\t\t<a onclick=\"showBlog()\">blog</a>\n");
      out.write("\t\t\t</li> -->\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<a onclick=\"showContact()\">contact</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"section\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<h1>accurate.reliable.fast</h1>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\tWhen it comes to finding answers to questions and getting results. Illumelabs is number one. No other diagnostic laboratory is faster, more reliable and accurate. Choose Illumelabs.\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"featured\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"article\">\n");
      out.write("\t\t\t\t<h2>Welcome to Illumelabs Diagnostic Center</h2>\n");
      out.write("\t\t\t\t<img src=\"images/diagnostic-center.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\tThis website template hahs been designed by <a href=\"http://www.freewebsitetemplates.com/\">Free Website Templates</a> for you, for free. You can replace all this text with your own text.\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\tYou can remove any link to our website from this website template, you're free to use this website template without linking back to us.\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\tf you're having problems editing this website template, then don't hesitate to ask for help on the <a href=\"http://www.freewebsitetemplates.com/forums/\">Forums</a>.\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<h3>hematology</h3>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\tBlood extraction using seismic energy for painless testing.\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"blog.jsp\" class=\"more\">read more</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<img src=\"images/hematology.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<h3>urine &amp; drug testing</h3>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\tAccurate and secure testing of urine for diseases and drugs and medicines.\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"blog.jsp\" class=\"more\">read more</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<img src=\"images/urine-and-drug-testing.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<h3>x-ray</h3>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\tFast and clear x-ray results. Youâll be assisted by our friendly staff all the way.\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"blog.jsp\" class=\"more\">read more</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<img src=\"images/x-ray.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<h3>pathology and dna</h3>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\tState of the art testing for DNA thatâs sure to be have fast and accurate results.\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"blog.jsp\" class=\"more\">read more</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<img src=\"images/pathology-and-dna.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"footer\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<span>2023 &copy; Illumelabs Diagnostic Center.</span><a href=\"#\" >Terms of Service</a> | <a href=\"#\" >Privacy Policy</a>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li id=\"facebook\">\n");
      out.write("\t\t\t\t\t<a href=\"http://freewebsitetemplates.com/go/facebook/\">facebook</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li id=\"twitter\">\n");
      out.write("\t\t\t\t\t<a href=\"http://freewebsitetemplates.com/go/twitter/\">twitter</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li id=\"googleplus\">\n");
      out.write("\t\t\t\t\t<a href=\"http://freewebsitetemplates.com/go/googleplus/\">googleplus</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li id=\"rss\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" >rss</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tfunction showHome(){\n");
      out.write("\t\t\talert(\"show index function\");\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"POST\",\n");
      out.write("\t\t\t\turl: \"index\",\n");
      out.write("\t\t\t\tdata: {show : \"show\"},\n");
      out.write("\t\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\t\talert(data);\n");
      out.write("\t\t\t\t\tif(data=='success'){\n");
      out.write("\t\t\t\t\t\talert(\"called ajax\");\n");
      out.write("\t\t\t\t\t\twindow.location.href='index.jsp';\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\terror: function(e){\n");
      out.write("\t\t\t\t\tconsole.log( e);\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t} \n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction showAbout(){\n");
      out.write("\t\t\talert('in about function');\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"GET\",\n");
      out.write("\t\t\t\t url: \"about\",\n");
      out.write("\t\t\t success: function(data){\n");
      out.write("\t\t\t\t \t\talert('in about data is :'+data);\n");
      out.write("\t\t\t }\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction showServices(){\n");
      out.write("\t\t\talert('in services function');\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"GET\",\n");
      out.write("\t\t\t\t url: \"services\",\n");
      out.write("\t\t\t success: function(data){\n");
      out.write("\t\t\t\t \t\talert('in services data is '+data);\n");
      out.write("\t\t\t }\n");
      out.write("\t\t\t });\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction showLocation(){\n");
      out.write("\t\t\talert('in location function');\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"GET\",\n");
      out.write("\t\t\t\t url: \"location\",\n");
      out.write("\t\t\t success:  function(data){\n");
      out.write("\t\t\t\t \t\talert('in location data is '+data);\n");
      out.write("\t\t\t }\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction showContact(){\n");
      out.write("\t\t\talert('in contact function');\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"GET\",\n");
      out.write("\t\t\t\turl : \"contact\",\n");
      out.write("\t\t\tsuccess : function(data){\n");
      out.write("\t\t\t\t\talert('in contact data is '+data);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* function showBlog(){\n");
      out.write("\t\t\talert('in blog function');\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"GET\",\n");
      out.write("\t\t\t\turl : \"blog\",\n");
      out.write("\t\t\tsuccess : function(data){\n");
      out.write("\t\t\t\talert('in blog data is '+data);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t})\n");
      out.write("\t\t} */\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
